config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root controller: :static_pages, action: :home

    get '/home', to: 'static_pages#home'
    get '/about', to: 'static_pages#about'
  end

  # Catch all route
  get '*path', to: 'static_pages#home', locale: I18n.default_locale, constraints: lambda { |req| req.path.exclude? 'rails/' }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  before_validation :sanitize_parameter

  validates :nickname, uniqueness: { case_sensitive: false }, presence: true


  private

  def sanitize_parameter
    self.nickname.squish!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  prepend_before_action :switch_locale

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end


  private

  def default_url_options
    {locale: I18n.locale}
  end

  def switch_locale
    I18n.locale = params[:locale] ||
                  http_accept_language.compatible_language_from(I18n.available_locales) ||
                  I18n.default_locale
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:about]

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/gravatar_helper.rb
# frozen_string_literal: true

module GravatarHelper
  # https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers

  def user_gravatar_tag(user)
    image_tag "#{Gravatar.url(user)}", alt: '', class: 'hvworkout__user-img'
  end

  def guest_gravatar_tag
    image_tag "#{Gravatar.url()}", alt: '', class: 'hvworkout__user-img'
  end

  def profile_gravatar_tag(user)
    content_tag :div, class: 'hvworkout__profile-gravatar' do
      link_to 'https://secure.gravatar.com/', target: '_blank', rel: 'noopener noreferrer' do
        (image_tag "#{Gravatar.url(user)}", alt: '', class: 'hvworkout__profile-gravatar-img') +
        (content_tag :div, class: 'hvworkout__profile-gravatar-link' do
          (content_tag :i, '', class: 'fas fa-edit').html_safe +
          (content_tag :span, "#{t('edit', scope: [:gravatar])}", class: 'sr-only') + " #{t('home', scope: [:gravatar])}"
        end)
      end
    end
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/layouts/_authentication.html.haml
-# frozen_string_literal: true
- if current_user
  .navbar-nav.nav-item.dropdown
    %a#userDropdown.nav-link.dropdown-toggle{aria: {expanded: 'false', haspopup: 'true'}, data: {toggle: 'dropdown'}, href: '#', role: 'menu'}
      = user_gravatar_tag current_user
      = current_user.nickname
    .dropdown-menu{aria: {labelledby: 'userDropdown'}}
      = link_to edit_registration_path(current_user), class: 'dropdown-item' do
        = fa_icon 'user'
        = t('.profile')
      .dropdown-divider
      = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
        = fa_icon 'sign-out-alt'
        = t('.log_out')

app/views/layouts/_brand.html.haml
-# frozen_string_literal: true
= link_to root_path, class: 'navbar-brand' do
  = image_pack_tag 'Stars.svg', class: 'hvworkout__brand-img'
  %span.hvworkout__d-xl-only.hvworkout__d-lg-only HVboom - HVWorkout
  %span.hvworkout__d-md-only.hvworkout__d-sm-only HVboom

app/views/layouts/_favicon.html.haml
-# frozen_string_literal: true
%link{href: "#{asset_pack_path 'media/favicons/apple-touch-icon.png'}", rel: "apple-touch-icon", sizes: "180x180"}/
%link{href: "#{asset_pack_path 'media/favicons/favicon-32x32.png'}", rel: "icon", sizes: "32x32", type: "image/png"}/
%link{href: "#{asset_pack_path 'media/favicons/favicon-16x16.png'}", rel: "icon", sizes: "16x16", type: "image/png"}/
%link{href: "#{asset_pack_path 'media/favicons/favicon.ico'}", rel: "shortcut icon"}/
%link{href: "#{asset_pack_path 'media/favicons/safari-pinned-tab.svg'}", rel: "mask-icon", color: "#5bbad5"}/
%link{href: "#{asset_pack_path 'media/favicons/site.webmanifest'}", rel: "manifest"}/
%meta{content: "HVWorkout", name: "apple-mobile-web-app-title"}/
%meta{content: "HVWorkout", name: "application-name"}/
%meta{content: "#ffffff", name: "theme-color"}/
%meta{content: "#2b5797", name: "msapplication-TileColor"}/
%meta{content: "#{asset_pack_path 'media/favicons/browserconfig.xml'}", name: "msapplication-config"}/

app/views/layouts/_messages.html.haml
-# frozen_string_literal: true
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert{class: "alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", role: 'alert'}
      %button.close{'aria-hidden': 'true', 'data-dismiss': 'alert', type: 'button'} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_multi_language.html.haml
-# frozen_string_literal: true
.navbar-nav.navbar-right.nav-item.dropdown
  %a#languageDropdown.nav-link.dropdown-toggle{aria: {label: "#{t('.language.selection')}", expanded: 'false', haspopup: 'true'}, data: {toggle: 'dropdown'}, href: '#', role: 'menu'}
    = image_pack_tag "flags/#{locale}.svg", class: 'hvworkout__language-img'
    %span.sr-only= t('.language.name', locale: locale)
  .dropdown-menu{aria: {labelledby: 'languageDropdown'}}
    - I18n.available_locales.reject{|l| l == locale}.sort.each do |locale|
      = link_to url_for(locale: locale), class: 'dropdown-item' do
        = image_pack_tag "flags/#{locale}.svg", class: 'hvworkout__language-img'
        = t('.language.name', locale: locale)

app/views/layouts/_navigation.html.haml
-# frozen_string_literal: true
%nav.navbar.fixed-top.navbar-expand-md.navbar-light.bg-light
  .container-md
    = render 'layouts/brand'
    = render 'layouts/authentication'
    %button.navbar-toggler{data: {target: '#navbar', toggle: 'collapse'}, aria: {controls: 'navbar', expanded: 'false', label: 'Toggle navigation'}, type: 'button'}
      %span.navbar-toggler-icon
    #navbar.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to home_path, class: 'nav-link' do
            = fa_icon 'home'
            = t('.home')
        %li.nav-item
          = link_to about_path, class: 'nav-link' do
            = fa_icon 'address-card'
            = t('.about')
    = render 'layouts/multi_language'

app/views/layouts/application.html.haml
-# frozen_string_literal: true
!!!
%html
  %head
    %meta{'http-equiv': 'content-type', content: 'text/html; charset=UTF-8'}/
    %meta{'http-equiv': 'content-language', content: "#{locale}"}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0, shrink-to-fit=no'}/
    %title= content_for?(:title) ? yield(:title) : t('.app.title')
    %meta{name: 'description', content: "#{content_for?(:description) ? yield(:description) : t('.app.description')}"}/
    = render 'layouts/favicon'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body.hvworkout{class: "#{controller.controller_name}"}
    %header
      = render 'layouts/navigation'
    %main.container-md.hvworkout__has-fixed-top-header{role: 'main'}
      = render 'layouts/messages'
      = yield
    %footer
      -if Rails.env.development?
        = console

app/views/shared/_actions.html.haml
-# frozen_string_literal: true
- back ||= back.nil?

= form.button :submit, submit, class: 'btn-primary'
= form.button :button, t('.reset'), type: :reset, class: 'btn-outline-secondary'
-if back
  = link_to t('.back'), :back, class: 'btn btn-outline-secondary float-right'

app/views/static_pages/_content.de.html.haml
-# frozen_string_literal: true
%h2 Content partial - Deutsche Version
%p Finde mich in app/views/static_pages/_content.de.html.haml

app/views/static_pages/_content.en.html.haml
-# frozen_string_literal: true
%h2 Content partial - English version
%p Find me in app/views/static_pages/_content.en.html.haml

app/views/static_pages/about.de.html.haml
-# frozen_string_literal: true
%h1 StaticPages#about - Deutsche Version
%p Find me in app/views/static_pages/about.de.html.haml

app/views/static_pages/about.en.html.haml
-# frozen_string_literal: true
%h1 StaticPages#about - English version
%p Find me in app/views/static_pages/about.en.html.haml

app/views/static_pages/home.html.haml
-# frozen_string_literal: true
%h1 StaticPages#home
%p Find me in app/views/static_pages/home.html.haml

= render 'content'